export const SET_VALUE = "SET_VALUE";
export const SET_SECOND_VALUE = "SET_SECOND_VALUE";
export const SET_OPERATOR = "SET_OPERATOR";
export const SET_FLOAT = "SET_FLOAT";
export const SET_NEGATIVE = "SET_NEGATIVE";
export const SET_OPERATOR_ENTERED = "SET_OPERATOR_ENTERED";
export const SET_RESULT_DISPLAYED = "SET_RESULT_DISPLAYED";